const actions = {
  GET_CARBOOKING_INFO: "GET_CARBOOKING_INFO",
  GET_CARBOOKING_INFO_SUCCESS: "GET_CARBOOKING_INFO_SUCCESS",
  GET_CARBOOKING_INFO_FAILURE: "GET_CARBOOKING_INFO_FAILURE",

  CHANGE_BOOKING_STATUS: "CHANGE_BOOKING_STATUS",
  CHANGE_BOOKING_STATUS_SUCCESS: "CHANGE_BOOKING_STATUS_SUCCESS",
  CHANGE_BOOKING_STATUS_FAILURE: "CHANGE_BOOKING_STATUS_FAILURE",

  CHANGE_BOOKING_PAYMENT: "CHANGE_BOOKING_PAYMENT",
  CHANGE_BOOKING_PAYMENT_SUCCESS: "CHANGE_BOOKING_PAYMENT_SUCCESS",
  CHANGE_BOOKING_PAYMENT_FAILURE: "CHANGE_BOOKING_PAYMENT_FAILURE",

  CHANGE_BOOKING_LOADER: "CHANGE_BOOKING_LOADER",
};

export default actions;
