const actions = {
  GET_COUPON_LIST: "GET_COUPON_LIST",
  GET_COUPON_LIST_SUCCESS: "GET_COUPON_LIST_SUCCESS",
  GET_COUPON_LIST_FAILURE: "GET_COUPON_LIST_FAILURE",
  GET_COPON_BY_ID: "GET_COPON_BY_ID",
  GET_COUPON_BY_ID_SUCCESS: "GET_COUPON_BY_ID_SUCCESS",
  GET_COUPON_BY_ID__FAILURE: "GET_COUPON_BY_ID__FAILURE",

  GENERATE_COUPON_CODE: "GENERATE_COUPON_CODE",
  GENERATE_COUPON_CODE_SUCCESS: "GENERATE_COUPON_CODE_SUCCESS",
  GENERATE_COUPON_CODE_FAILURE: "GENERATE_COUPON_CODE_FAILURE",

  CREATE_NEW_COUPON: "CREATE_NEW_COUPON",
  CREATE_NEW_COUPON_SUCCESS: "CREATE_NEW_COUPON_SUCCESS",
  CREATE_NEW_COUPON_FAILURE: "CREATE_NEW_COUPON_FAILURE",

  REMOVE_COUPON: "REMOVE_COUPON",
  REMOVE_COUPON_SUCCESS: "REMOVE_COUPON_SUCCESS",
  REMOVE_COUPON_FAILURE: "REMOVE_COUPON_FAILURE",

  GET_USERS_AGENCY_LIST: "GET_USERS_AGENCY_LIST",
  GET_USERS_AGENCY_LIST_SUCCESS: "GET_USERS_AGENCY_LIST_SUCCESS",
  GET_USERS_AGENCY_LIST_FAILURE: "GET_USERS_AGENCY_LIST_FAILURE",
};

export default actions;
