const actions = {

    GET_CUSTOMER_LIST: 'GET_CUSTOMER_LIST',
    GET_CUSTOMER_LIST_SUCCESS: 'GET_CUSTOMER_LIST_SUCCESS',
    GET_CUSTOMER_LIST_FAILURE: 'GET_CUSTOMER_LIST_FAILURE',
    
    GET_CARD_LIST: 'GET_CARD_LIST',
    GET_CARD_LIST_SUCCESS: 'GET_CARD_LIST_SUCCESS',
    GET_CARD_LIST_FAILURE: 'GET_CARD_LIST_FAILURE',

    SET_CUSTOMER_STATUS: 'SET_CUSTOMER_STATUS',
    SET_CUSTOMER_STATUS_SUCCESS: 'SET_CUSTOMER_STATUS_SUCCESS',
    SET_CUSTOMER_STATUS_FAILURE: 'SET_CUSTOMER_STATUS_FAILURE',

    SETUP_NEW_CUSTOMER: "SETUP_NEW_CUSTOMER",
    SETUP_NEW_CUSTOMER_SUCCESS: "SETUP_NEW_CUSTOMER_SUCCESS",
    SETUP_NEW_CUSTOMER_FAILURE: "SETUP_NEW_CUSTOMER_FAILURE",

    REMOVE_CUSTOMER_DETAILS: "REMOVE_CUSTOMER_DETAILS",
    REMOVE_CUSTOMER_DETAILS_SUCCESS: "REMOVE_CUSTOMER_DETAILS_SUCCESS",
    REMOVE_CUSTOMER_DETAILS_FAILURE: "REMOVE_CUSTOMER_DETAILS_FAILURE"
};

export default actions;