const actions = {

    GET_CMS_INFO: 'GET_CMS_INFO',
    GET_CMS_INFO_SUCCESS: 'GET_CMS_INFO_SUCCESS',
    GET_CMS_INFO_FAILURE: 'GET_CMS_INFO_FAILURE',

    GET_CMS_INFO_BYID: 'GET_CMS_INFO_BYID',
    GET_CMS_INFO_BYID_SUCCESS: 'GET_CMS_INFO_BYID_SUCCESS',
    GET_CMS_INFO_BYID_FAILURE: 'GET_CMS_INFO_BYID_FAILURE',

    CMSIUD_STATUS: 'CMSIUD_STATUS',
    CMSIUD_STATUS_SUCCESS: 'CMSIUD_STATUS_SUCCESS',
    CMSIUD_STATUS_FAILURE: 'CMSIUD_STATUS_FAILURE',

    CHANGE_CMS_STATUS: 'CHANGE_CMS_STATUS',
    CHANGE_CMS_STATUS_SUCCESS: 'CHANGE_CMS_STATUS_SUCCESS',
    CHANGE_CMS_STATUS_FAILURE: 'CHANGE_CMS_STATUS_FAILURE',

    REMOVE_CMS_DETAILS: 'REMOVE_CMS_DETAILS',
    REMOVE_CMS_DETAILS_SUCCESS: 'REMOVE_CMS_DETAILS_SUCCESS',
    REMOVE_CMS_DETAILS_FAILURE: 'REMOVE_CMS_DETAILS_FAILURE',

    GET_FAQ_INFO: 'GET_FAQ_INFO',
    GET_FAQ_INFO_SUCCESS: 'GET_FAQ_INFO_SUCCESS',
    GET_FAQ_INFO_FAILURE: 'GET_FAQ_INFO_FAILURE',

    GET_FAQ_INFO_BYID: 'GET_FAQ_INFO_BYID',
    GET_FAQ_INFO_BYID_SUCCESS: 'GET_FAQ_INFO_BYID_SUCCESS',
    GET_FAQ_INFO_BYID_FAILURE: 'GET_FAQ_INFO_BYID_FAILURE',

    FAQIUD_STATUS: 'FAQIUD_STATUS',
    FAQIUD_STATUS_SUCCESS: 'FAQIUD_STATUS_SUCCESS',
    FAQIUD_STATUS_FAILURE: 'FAQIUD_STATUS_FAILURE',

    CHANGE_FAQ_STATUS: 'CHANGE_FAQ_STATUS',
    CHANGE_FAQ_STATUS_SUCCESS: 'CHANGE_FAQ_STATUS_SUCCESS',
    CHANGE_FAQ_STATUS_FAILURE: 'CHANGE_FAQ_STATUS_FAILURE',

    REMOVE_FAQ_DETAILS: 'REMOVE_FAQ_DETAILS',
    REMOVE_FAQ_DETAILS_SUCCESS: 'REMOVE_FAQ_DETAILS_SUCCESS',
    REMOVE_FAQ_DETAILS_FAILURE: 'REMOVE_FAQ_DETAILS_FAILURE',
};

export default actions;